version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - polls_pg_data:/stockdb/postgresql


  redis:
    image: redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
  
    volumes:
      - polls_redis_data:/redis/data

 
volumes:
  polls_pg_data:
  polls_redis_data: